{"_default": {"1": {"app_name": "test_final_1", "docker_image": "digitalocean/flask-helloworld", "docker_port": "5000", "dashboard_url": "/dashboard/test_final_1", "app_url": "http://test_final_1.hoster.local", "user_id": "Divyash"}}, "instances": {"1": {"provisioned": true, "provisioning": false, "docker_image": "digitalocean/flask-helloworld", "docker_port": "5000", "user_id": "Divyash", "machine_url": "http://192.168.196.125", "instance_url": "http://192.168.196.125:40871", "container_id": "65168f1a09ea71144b28096dae5c4192a7bd57c48186a46a879398f264de01ed"}, "2": {"provisioned": false, "provisioning": false, "docker_image": "digitalocean/flask-helloworld", "docker_port": "5000", "user_id": "Divyash", "machine_url": "http://192.168.196.27", "error": "HTTPConnectionPool(host='192.168.196.27', port=8080): Max retries exceeded with url: /build-from-hub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c00202df0>: Failed to establish a new connection: [Errno 113] No route to host'))"}, "3": {"provisioned": true, "provisioning": false, "docker_image": "digitalocean/flask-helloworld", "docker_port": "5000", "user_id": "Divyash", "machine_url": "http://192.168.196.27", "instance_url": "http://192.168.196.27:59171", "container_id": "c5ed4559796250305d5b0d71c2f5a3bfc30826e1891ddbd936b24396915d2521"}}}